### ISSUE TITLE
Error when compiling for osx or ios on mac

### ISSUE THREAD

**Issue by indiejames** [effekseer/EffekseerForGodot3#9]
Getting an error when attempting to compile for osx or ios on my mac. I have both python3 and scons installed.

```
$ python3 Dev/Cpp/build.py platorm=ios
Traceback (most recent call last):
  File "/Users/jnorton/github/EffekseerForGodot3/Dev/Cpp/build.py", line 24, in <module>
    import_generate_bindings()
  File "/Users/jnorton/github/EffekseerForGodot3/Dev/Cpp/build.py", line 20, in import_generate_bindings
    os.chdir(os.path.join(cwd, "godot-cpp"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jnorton/github/EffekseerForGodot3/godot-cpp'
```

**Comment by durswd** [comment]
https://github.com/effekseer/EffekseerForGodot3/blob/main/.github/workflows/build.yml#L72

The document is wrong

Please call

```
cd ./Dev/Cpp
python3 build.py platform=ios
```

**Comment by durswd** [comment]
I fixed

https://github.com/effekseer/EffekseerForGodot3/commit/eef7d5b38d1ee84165f8ea04d444e071dccef9bd
